### ISSUE TITLE
Read instances for nominal types

### ISSUE THREAD

**Issue by Jaxan** [szynwelski/nlambda#4]
It would be useful (at least to me) to have a Read instance for Atom. I am planning to read constants (not variables), so that I can parse counter examples from an external teacher.

I want to know whether there was a reason to leave it out?

**Comment by szynwelski** [comment]
There was no reason. I will add Read instances in a few days.

**Comment by Jaxan** [comment]
I created a branch (https://github.com/szynwelski/nlambda/tree/read-atoms), because I needed it now ;-). It does not implement a full Read instance, just the things I use.

**Comment by szynwelski** [comment]
I added Read instances to all nominal types.
It was more difficult than i expected.
