### ISSUE TITLE
Inference is broken

### ISSUE THREAD

**Issue by Jaxan** [szynwelski/nlambda#6]
Hi,

Inference is broken. This might be my fault: when I added generic instances for the NominalType, I split the Ord/Nominal type classes, and added the constraint kind `NominalType a = (BareNominalType a, Ord a)`, so that all the old code did not need to be changed...

The following does not compile, as the type of `ns` cannot be inferred to be `ns :: NominalType a => [a] -> Set a`.

```
module Main where

import NLambda
import qualified Prelude
import Prelude (print, Int, Char)

ns = fromList

main = do
  print (ns ['a' :: Char])
  print (ns [1 :: Int])
```

One solution is to move `Ord` as a context to `NominalType` again (like it was before). Then it'll be hard to write the generic instances.

Another option is to rewrite a bit, leaving `Ord` and `NominalType` separate classes, but then many functions need to change (as many depend on both).

More options? Maybe this is a feature we would like to have in ghc. I will try to make a small example where the same thing breaks.

**Comment by Jaxan** [comment]
I was completely wrong to blame myself or NLambda.
This was a simple consequence of the **monomorphism restriction**. So the "error" is exactly what one should expect given this rule in Haskell...

Anyways, I am still not too happy about the way I set up the generic instances for `NominalType`. But that's for another time.

**Comment by szynwelski** [comment]
Nevertheless, I am in favour of moving `Ord` back to the context of `NominalType`. I understand the only problem with this are types with custom order. The `Ord` context is required for `Data.Map` which is used in `Set` and `Variants`. But `Data.Map` needs `Ord` to check equality efficiently and the order does not affect the value of nominal set and variants. Am I right?

**Comment by Jaxan** [comment]
Let's discuss this `Ord`-issue at #7
