### ISSUE TITLE
Numbers in atom names make the parser fail

### ISSUE THREAD

**Issue by Jaxan** [szynwelski/nlambda#8]
When creating an atom with a number in the string, the SMT-parsing fails

```
> simplify $ atom "a0" `neq` atom "b" /\ atom "c" `neq` atom "d"
*** Exception: Fail to parse SMT Solver output:
- not parsed output: "(not (= a0 b))\n  (not (= c d))\n  :precision precise :depth 1)\n)\n"
- list of contexts in which the error occurred: [")"]
- error message: "Failed reading: satisfyWith"

CallStack (from HasCallStack):
  error, called at /home/joshua/Documents/Projects/popl-artifact-mod/nlambda-git/src/Nominal/Formula/Solver.hs:220:25 in main:Nominal.Formula.Solver
```

**Comment by szynwelski** [comment]
I fixed parsing output of SMT solver. Additionally, I introduced a validation of variable names. They must be alhpanumeric and start with a letter.

**Comment by Jaxan** [comment]
Is it true that variable names should be alphanumeric only?
The internal names often include subscripting, so I can imagine that people want to use '_' themselves.

Thanks for fixing this so quickly :)

**Comment by szynwelski** [comment]
I can expand the set of allowed characters. What do you think, what characters should we allow?

**Comment by Jaxan** [comment]
Should correspond to what Z3 accepts. I did a quick search but did not find the formal syntax. I guess it's not much more than alphanumeric + '_', maybe the dot '.'.

**Comment by szynwelski** [comment]
I expanded the set of allowed characters with underscore, dot and hyphen.
